name: update-dotnet-sdk

env:
  TERM: xterm

on:
  schedule:
    - cron:  '00 19 * * TUE'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-dotnet-sdk:
    name: Update .NET SDK
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'martincostello' }}

    steps:

    - name: Checkout code
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Update .NET SDK
      id: update-dotnet-sdk
      uses: martincostello/update-dotnet-sdk@6cfd047b0c2ce72ea0e22708bc1918a3d912c050 # v2.2.0
      with:
        labels: "dependencies,.NET"
        repo-token: ${{ secrets.ACCESS_TOKEN }}
        user-email: ${{ vars.GIT_COMMIT_USER_EMAIL }}
        user-name: ${{ vars.GIT_COMMIT_USER_NAME }}
