name: update-dotnet-sdk

env:
  TERM: xterm

on:
  schedule:
    - cron:  '00 19 * * TUE'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-dotnet-sdk:
    name: Update .NET SDK
    runs-on: ubuntu-latest
    if: github.repository_owner == 'martincostello'

    steps:

    - name: Checkout code
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Update .NET SDK
      id: update-dotnet-sdk
      uses: martincostello/update-dotnet-sdk@68300a9120c745ca0ff120e2940b63ef1ad2c725 # v3.2.2
      with:
        labels: 'dependencies,.NET'
        repo-token: ${{ secrets.ACCESS_TOKEN }}
        user-email: ${{ vars.GIT_COMMIT_USER_EMAIL }}
        user-name: ${{ vars.GIT_COMMIT_USER_NAME }}
