name: update-dotnet-sdk

env:
  TERM: xterm

on:
  schedule:
    - cron:  '00 19 * * TUE'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-dotnet-sdk:
    name: Update .NET SDK
    runs-on: ubuntu-latest
    if: github.repository_owner == 'martincostello'

    steps:

    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Update .NET SDK
      id: update-dotnet-sdk
      uses: martincostello/update-dotnet-sdk@b3d5ca8064ec275f7a1d0b9640d28a57ab94090b # v3.1.1
      with:
        labels: 'dependencies,.NET'
        repo-token: ${{ secrets.ACCESS_TOKEN }}
        user-email: ${{ vars.GIT_COMMIT_USER_EMAIL }}
        user-name: ${{ vars.GIT_COMMIT_USER_NAME }}
