name: update-dotnet-sdk

env:
  TERM: xterm

on:
  schedule:
    - cron:  '00 19 * * TUE'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-dotnet-sdk:
    name: Update .NET SDK
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'martincostello' }}

    steps:

    - name: Checkout code
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Update .NET SDK
      id: update-dotnet-sdk
      uses: martincostello/update-dotnet-sdk@ff9a6f247704ef1b77eb3c478070d8fa69c2360e # v2.2.3
      with:
        labels: "dependencies,.NET"
        repo-token: ${{ secrets.ACCESS_TOKEN }}
        user-email: ${{ vars.GIT_COMMIT_USER_EMAIL }}
        user-name: ${{ vars.GIT_COMMIT_USER_NAME }}
